name = "cloudflare-api"
main = "src/index.js"
compatibility_date = "2024-03-07"

[vars]
DOMAIN = "http://localhost:5173"

[env.production.vars]
DOMAIN = "https://hairbynoora.com.au"
BREVO_FROM_EMAIL = "bookings@hairbynoora.com.au"
#BREVO_FROM_EMAIL= "burgerfries2021@gmail.com"
BREVO_FROM_NAME = "Hair by Noora"
BREVO_BCC_EMAIL = "bookings@hairbynoora.com.au"
#BREVO_BCC_EMAIL= "burgerfries2021@gmail.com"
FIREBASE_AUTH_DOMAIN= "hair-by-noora.firebaseapp.com"
FIREBASE_PROJECT_ID= "hair-by-noora"
FIREBASE_STORAGE_BUCKET= "hair-by-noora.appspot.com"
FIREBASE_MESSAGING_SENDER_ID= "372795756197"
FIREBASE_APP_ID= "1:372795756197:web:59c8eb91f65f42f26bc74c"
TIMEZONE="Australia/Melbourne"
GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY= "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCyXbYfbHWF5PbR\n+ytU4EsgIHb3C8edvL9fP3QQQl1CvbrpC4nlnWWQZhXUlue/6AXZFadwQ7nUt2Vb\nC0I1owFGcWbJyclUWu8sqUiQQ4DLXc3ZDmLtuxl3qJnyals/ObbRsJOsrQgJFaa+\nFJgdq2Kfc+7GW9sULXp0G/Q8lshsbZDlMA8kbTQlJAD+PSOi05urnvhROHS2QX52\nP25zklkedjA+iRCPvFKuf01bcneJKnHZb8AOzgSIXW3S2Fo2+PUnbyGiQV0u6ilg\nJo6P6tPWi/vgCnGSpNSbo3QdRjQxtb3LjhiW7arL/xE4saiXJrgK+8t6D30sQ2dU\n0rkrnO/zAgMBAAECggEAMNzGMyaRrWvzh8Ogc8B8JCFwpa3m8dnOrUejQn8DsHBs\nf0IndS0gsSWeLl5mv2ZPD9DETVdoVZMmI4JakXoFs+gGChqK2l6M7fW0CL1NT6jz\nZtZvmIOsbuDTx5qGQ7RKVnhihCfkryRsyN64a0xTmK34SAPK6OSqiptL1btSzYzj\nQdPok1EEuRxG1BrnwrLyrZc9ouXSx72EKeBrofmNOXSRi96OPmGddJksEsgOO7tR\n0XbtHw1Z6FInY6sH7/E3UmPWiR9jx8u+HsFLX2vKwO8eCsB149uBJpG+h1Z1SHDS\nA+uyHgFbQDQHbSof6QqAr1rLC7+hkjqyJ8eX8EOb2QKBgQDdUNa3GdWtbpT7MjwJ\ncDZXNxky1h8zzl6MyUWlzREi63FLGaXKO21K/UEokgN8L/A6ypoUEIjCO4F+zyT/\nRSZCnb45QPdWXkX3N3fG4ju31xdHYWv3jBY1DUq2EifwmwzfAa2gW1mXvoh4uNTj\nP4ubdDJ3ncTkqp1lnbtJUvNs6QKBgQDOUbxGTplhHDJ/GbLWFnxAlyUKtrdiSuAz\nVxXIBHKqJY+/8W66CQ0po9+A/mPLno+yiY8S83oRZ0mTX8BHkvZkJaz80Fb7e8kQ\nXW9yUhavRsY+7jewLyH9knRq9Gkt7F6PT/HSiFBclB1cVKKki0SI2lpxhM1rA9DK\n6wFW4Xk8ewKBgEX3m5oRadNFpYXwsLhPKG7UNXwz43NuZ8fcjc9IEIXYp12Vwys3\nNGtDu4jG+KEXSrxbdvCm9YVqaJsdg9XMF7dxxUS2fDtq3HW2rIBM35JURsDDVO3S\n9OZayGbdQJE5g40xK6IJnz5w9xYrYOpjGZDQ4G+eijO8mLwabK5WsiyZAoGAInJn\nGt34ocwRakMiJrhuWmJh3t4O1CxoLmo1ysVjV6EZ1RQ8RndIaVFg+ap/gvmgSFDL\nQIDCOrGiCScNdWXGGYZo0XT/cNGECmVvPAkUnIMWil8/kPztkean5UuVXAOA7jCM\n0XfM4wgfttCyrwJJmQfL3fQsT9e9PoPqH1VZ5o0CgYBTN2cqFWaRv3SPjFmcyZ4y\n0WE97GmQubYTY1K3O4PusZi2acjl+yEu3gSEcXcLzUvV3/nsLrsU44vyzQrt65RB\nPu8fCD2Y30z0UmgBNmVlqd8KMPuDolykaKjlCjQTw57MZUvN28g0Kln2xFLa1YT/\na8czEJK8GyzvnEUSECT3Rg==\n-----END PRIVATE KEY-----"
GOOGLE_CALENDAR_ID= "burgerfries2021@gmail.com"
GOOGLE_PROJECT_ID= "plenary-charge-463701-r2"
GOOGLE_SERVICE_ACCOUNT_EMAIL= "hair-by-noora@plenary-charge-463701-r2.iam.gserviceaccount.com"

# Use these values in your .dev.vars file
# STRIPE_SECRET_KEY = ""
# STRIPE_WEBHOOK_SECRET = ""
# FIREBASE_API_KEY = ""
# FIREBASE_AUTH_DOMAIN = ""
# FIREBASE_PROJECT_ID = ""
# FIREBASE_STORAGE_BUCKET = ""
# FIREBASE_MESSAGING_SENDER_ID = ""
# FIREBASE_APP_ID = ""
# BREVO_API_KEY = ""
# BREVO_TEMPLATE_ID = ""

[observability]
enabled = true
