name = "cloudflare-api"
main = "src/index.js"
compatibility_date = "2024-03-07"

[vars]
DOMAIN = "http://localhost:5173"

[env.production.vars]
DOMAIN = "https://hairbynoora.com.au"


[[rules]]
type = "ESModule"
globs = ["**/*.js"]

[build]
command = ""

[observability]
enabled = true
